title: "Bhuvana Nagaraj"
description: "Software Engineer • QA Automation • AI/ML"
url: "https://<your-username>.github.io"
theme: null
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

locale: en-US
logo: /assets/img/avatar.png
repository: <your-username>/<your-repo>
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: "Bhuvana Nagaraj"
  avatar: /assets/img/avatar.png
  bio: "SWE (Samsung alum). QA Automation • Camera stack • AI/ML."
  location: "San Mateo, CA"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Bhuvana-Nagaraj-gowda"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/bhuvana-nagaraj04"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:bhuvana.nagaraj.work@gmail.com"

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope: { path: "", type: "projects" }
    values: { layout: single, author_profile: true }
  - scope: { path: "" }
    values: { layout: home, classes: wide }

paginate: 6
paginate_path: "/page:num/"
